# Generated by Django 2.2.6 on 2019-10-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Mobile_Numer',
            new_name='Mobile',
        ),
        migrations.AlterField(
            model_name='client',
            name='Address',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='Dob',
            field=models.CharField(default='', max_length=10),
        ),
    ]
